export const ADD_JOB = 'ADD_JOB'
export const REMOVE_JOB = 'REMOVE_JOB'
export const FILL_DATA = 'FILL_DATA'
export const FILL_DATA_LOADING = 'FILL_DATA_LOADING'
export const FILL_DATA_ERROR = 'FILL_DATA_ERROR'
export const ADD_OFFSET = 'ADD_OFFSET'
export const ADD_SEARCH = 'ADD_SEARCH'
export const ADD_CATEGORY = 'ADD_CATEGORY'
